### PR TITLE
6be88adcffddd2c4a7e77228f22f3f80

### PR DESCRIPTION
**Pull request by LynnLong000**
git@github.com:LynnPLong/6be88adcffddd2c4a7e77228f22f3f80.git

### CODE REVIEW

**Comment by risoscino** [comment]
Lynn,

all of your code should be in your md5 folder, not in the base directory.

-Christopher

**Comment by LynnLong000** [comment]
Christopher,
I just fixed it. sorry it took me a while to figure that out

**Comment by risoscino** [comment]
Looks like you’re still committing to the base directory.

Be sure you have created a new directory and all your contributions are in that.

[signatureSeal]Christopher Fowler
Chief Innovation Officer | Director of IT
RI Department of State  |  Secretary of State Nellie M. Gorbea
Email: cfowler@sos.ri.govmailto:cfowler@sos.ri.gov  | Website:  www.sos.ri.govhttp://www.sos.ri.gov/  | Twitter: @RISecStatehttps://twitter.com/RISecState
148 W. River Street, Providence RI 02904 | 401-222-1326

Our Mission: The Rhode Island Department of State engages and empowers all Rhode Islanders by making government more accessible and transparent, encouraging civic pride, enhancing commerce and ensuring that elections are fair, fast and accurate.

**Comment by LynnLong000** [comment]
git@github.com:LynnPLong/6be88adcffddd2c4a7e77228f22f3f80.git

**Pull request closed without merging**
